# Generated by Django 5.0.3 on 2024-03-12 02:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_year', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'ordering': ['school_year'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('course_title', models.CharField(max_length=150)),
                ('units', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'ordering': ['subject_code'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(choices=[('0', 'Intersession'), ('1', 'First Semester'), ('2', 'Second Semester')], default='0', max_length=20)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedo.schoolyear')),
            ],
            options={
                'ordering': ['-school_year', '-semester'],
            },
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('subject_code', 'course_title', 'units'), name='subj_uniq'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('school_year', 'semester'), name='sy_and_sem_uniq'),
        ),
    ]
