# Generated by Django 5.0.3 on 2024-03-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150)),
                ('given_name', models.CharField(max_length=150)),
                ('middle_initial', models.CharField(blank=True, default='', max_length=5)),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='professor',
            constraint=models.UniqueConstraint(fields=('last_name', 'given_name', 'middle_initial'), name='prof_uniq'),
        ),
    ]
