# Generated by Django 5.0.3 on 2024-03-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolyear',
            name='school_year',
            field=models.CharField(max_length=150),
        ),
    ]
