# Generated by Django 5.0.3 on 2024-03-12 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedo', '0002_professor_professor_prof_uniq'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='professor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedo.professor'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedo.subject'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='time',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedo.time'),
        ),
    ]
