# Generated by Django 5.0.3 on 2024-03-25 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedo', '0002_alter_schoolyear_school_year'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['department', 'subject_code']},
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedo.department'),
        ),
    ]
