# Generated by Django 5.0.3 on 2024-03-26 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedo', '0003_alter_subject_options_subject_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='time',
        ),
        migrations.AddField(
            model_name='time',
            name='end_time',
            field=models.TimeField(default='00:00:00', max_length=9),
        ),
        migrations.AddField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default='00:00:00', max_length=9),
        ),
        migrations.AlterField(
            model_name='time',
            name='day',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='time',
            name='modality',
            field=models.CharField(default='onsite', max_length=20),
        ),
        migrations.AlterField(
            model_name='time',
            name='room',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('time_created', models.DateField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedo.schedule')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedo.usertable')),
            ],
        ),
    ]
