# Generated by Django 5.0.3 on 2024-03-26 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedo', '0003_alter_subject_options_subject_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='time',
            name='time',
        ),
        migrations.AddField(
            model_name='time',
            name='end_time',
            field=models.TimeField(default='00:00:00', max_length=9),
        ),
        migrations.AddField(
            model_name='time',
            name='start_time',
            field=models.TimeField(default='00:00:00', max_length=9),
        ),
        migrations.AlterField(
            model_name='time',
            name='day',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='time',
            name='modality',
            field=models.CharField(default='onsite', max_length=20),
        ),
        migrations.AlterField(
            model_name='time',
            name='room',
            field=models.CharField(default='', max_length=20),
        ),
    ]
