# Generated by Django 5.0.3 on 2024-03-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedo', '0004_remove_time_time_time_end_time_time_start_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.ManyToManyField(to='schedo.schedule')),
            ],
        ),
    ]
