# Generated by Django 5.0.3 on 2024-03-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedo', '0006_userschedule_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSchedule',
        ),
    ]
