# Generated by Django 5.0.3 on 2024-03-12 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department_name', models.CharField(max_length=150, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=150)),
                ('given_name', models.CharField(max_length=150)),
                ('middle_initial', models.CharField(blank=True, default='', max_length=5)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profs_to_pick.department')),
            ],
            options={
                'ordering': ['last_name'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profs_to_pick.professor')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedo.subject')),
            ],
        ),
        migrations.AddConstraint(
            model_name='professor',
            constraint=models.UniqueConstraint(fields=('last_name', 'given_name', 'middle_initial'), name='prof_uniq'),
        ),
    ]
