# Generated by Django 5.0.3 on 2024-04-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profs_to_pick', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='sentiment',
            field=models.CharField(choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Negative', 'Negative')], default='Positive', max_length=10),
        ),
    ]
