# Generated by Django 5.0.3 on 2024-03-12 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profs_to_pick', '0002_remove_review_professor_delete_professor'),
        ('schedo', '0003_schedule_professor_alter_schedule_subject_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.AddField(
            model_name='review',
            name='professor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedo.professor'),
        ),
        migrations.AlterField(
            model_name='review',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='schedo.subject'),
        ),
    ]
