# Generated by Django 5.0.3 on 2024-03-12 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_grade_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='semester',
        ),
    ]
