# Generated by Django 5.0.3 on 2024-04-23 17:52

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_grade_options_grade_semester_and_more'),
        ('schedo', '0008_usertable_userschedule'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['username', '-semester', 'grade']},
        ),
        migrations.RemoveConstraint(
            model_name='grade',
            name='sem_and_sub__uniq',
        ),
        migrations.AddField(
            model_name='grade',
            name='username',
            field=models.CharField(default='', max_length=150, verbose_name=django.contrib.auth.models.User),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('username', 'semester', 'subject'), name='sem_and_sub__uniq'),
        ),
    ]
