# Generated by Django 5.0.3 on 2024-04-23 16:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_grade_options_grade_semester_and_more'),
        ('schedo', '0008_usertable_userschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grade',
            options={'ordering': ['username', '-semester', 'grade']},
        ),
        migrations.RemoveConstraint(
            model_name='grade',
            name='sem_and_sub__uniq',
        ),
        migrations.AddField(
            model_name='grade',
            name='username',
            field=models.ForeignKey(default='', limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('username', 'semester', 'subject'), name='sem_and_sub__uniq'),
        ),
    ]
